spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: dbba6a2af6f351bc183f
            client-secret: 469c2ee409e8309fc6e9cdaaa280b7f4097b4f4f
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
