server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=chatflow
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: chatflow
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    properties:
      hibernate:
        default_schema: chatflow
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

jwt:
  secret-key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDZ5QIeI0ioHDYGU0RMwGti6Z9/2SReCeFnYZJY5xsbFWRiU"

google:
  client-id: "393039598382-7k652bidcub7m5fnltcdb776q4kur28g.apps.googleusercontent.com"