package com.hellobirdie.chatflow.dto.node;

import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.OffsetDateTime;

@Getter
@Setter
@NoArgsConstructor
@ToString
public class NodeGetDto {

    private Long id; // bigserial usually translates to Long in Java
    private Long mindmapId; // int8 is a Long in Java
    private Long conversationPairId; // int8 is a Long in Java
    private String userMessage; // text translates to String
    private String aiMessage; // text translates to String
    private String note; // text translates to String
    private String color; // varchar translates to String, with a max length of 30 characters
    private OffsetDateTime updateTime; // timestamptz is a timestamp with time zone, which can be represented by ZonedDateTime in Java
    private OffsetDateTime createTime; // timestamptz is a timestamp with time zone, which can be represented by ZonedDateTime in Java
    private Integer x; // int8 is a Long in Java, but considering the context, Integer might be sufficient
    private Integer y; // int8 is a Long in Java, but considering the context, Integer might be sufficient

    // With Lombok, there's no need for explicit getters, setters, or toString method as they're auto-generated by the annotations.

}
