CREATE TABLE "ai"(
    "id" BIGSERIAL PRIMARY KEY,
    "model" INT,
    "update_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "create_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "is_deleted" BOOLEAN DEFAULT FALSE NOT NULL
);