CREATE TABLE "user_setting"(
    "id" BIGINT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
    "language" VARCHAR(30),
    "update_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "create_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "is_deleted" BOOLEAN DEFAULT FALSE NOT NULL
);