CREATE TABLE "mindmap_setting"(
    "id" BIGINT PRIMARY KEY REFERENCES mindmap(id) ON DELETE CASCADE,
    "background_color" VARCHAR(30) NOT NULL,
    "update_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "create_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "is_deleted" BOOLEAN DEFAULT FALSE NOT NULL
);