CREATE TABLE "user" (
    "id" BIGSERIAL PRIMARY KEY,
    "email "VARCHAR(255) UNIQUE NOT NULL,
    "username" VARCHAR(255) NOT NULL,
    "password" VARCHAR(30) NOT NULL,
    "avatar" VARCHAR(255) NOT NULL,
    "subscription_level" INT NOT NULL,
    "update_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "create_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "is_deleted" BOOLEAN DEFAULT FALSE NOT NULL
);